package org.ivcode.aimo.core.model

import org.ivcode.aimo.core.chatservice.SystemMessageCallback
import tools.jackson.databind.JsonNode

/**
 * Aimo-owned abstraction for chat model execution.
 *
 * This forms the provider-agnostic execution seam between Aimo core and concrete
 * model integrations. Callers should depend only on these Aimo-owned contracts.
 *
 * ## Token Usage and Multi-Turn Orchestration
 * Each `call` method represents a **single provider invocation** and returns usage for that call only:
 * - [AimoChatResponse.usage] reflects tokens consumed in **this specific engine call**
 * - Multi-turn exchanges (tool calls and retries) are **not** orchestrated inside the engine
 * - Instead, orchestration happens at the core layer ([AimoChatClientImpl]) which loops and calls the engine multiple times
 * - Request-level usage aggregation (summing across tool calls and retries) happens in the core, not the engine
 * - Engine implementations have no knowledge of higher-level tool-call loops; they only handle single-turn model calls
 */
interface AimoChatEngine {
    val options: AimoChatOptions

    /**
     * Non-streaming chat execution for a single provider call.
     *
     * Blocks until the model responds and returns a single response.
     * This represents a **single turn** in a provider interaction; orchestration of
     * multi-turn exchanges (e.g., tool calls and retries) occurs at the core layer
     * ([AimoChatClientImpl]), not inside the engine.
     *
     * @param prompt The chat prompt with messages, tools, and options
     * @return Response with messages generated by the model and token usage for this specific provider call
     */
    fun call(prompt: AimoPrompt): AimoChatResponse

    /**
     * Streaming chat execution with incremental callback updates for a single provider call.
     *
     * Invokes the callback incrementally as the response is generated. Callbacks receive
     * streaming updates; they are useful for displaying progress to the caller.
     *
     * The final returned [AimoChatResponse] represents a **single provider turn**:
     * - [AimoChatResponse.messages] contains messages generated by this invocation
     * - [AimoChatResponse.usage] reflects tokens consumed in this specific call only
     *
     * Multi-turn orchestration (tool calls, retries) happens in the core layer outside the engine.
     *
     * @param prompt The chat prompt with messages, tools, and options
     * @param callback Invoked for each incremental streaming update; use for progress/display only
     * @return Final response from this provider call with messages and token usage for this call only
     */
    fun call(prompt: AimoPrompt, callback: (AimoChatResponse) -> Unit): AimoChatResponse
}

/**
 * Provider-agnostic chat tuning options.
 *
 * Expressed as a Kotlin data class so it is easy to serialize, copy, merge,
 * and document.
 *
 * Notes for future adapters and parsing code:
 * - Every property is nullable so an option may be omitted and resolved by the
 *   backing provider or model default.
 * - [model] identifies the target model name when a provider supports runtime
 *   model selection.
 * - [stopSequences] should be forwarded in order, preserving duplicates only if
 *   the downstream provider explicitly supports them.
 * - [providerOptions] is an escape hatch for provider-specific flags while the
 *   portable surface area is still evolving.
 */
data class AimoChatOptions (
    val model: String? = null,
    val temperature: Double? = null,
    val maxTokens: Int? = null,
    val topP: Double? = null,
    val topK: Int? = null,
    val frequencyPenalty: Double? = null,
    val presencePenalty: Double? = null,
    val stopSequences: List<String> = emptyList(),
    val providerOptions: Map<String, Any> = emptyMap(),
)

/**
 * Provider-agnostic prompt contract used by Aimo chat engines.
 *
 * Ordered chat messages are the single required input.
 *
 * [options] allows per-request overrides of model tuning parameters. When it is
 * `null`, callers are deferring entirely to the model's configured defaults.
 */
data class AimoPrompt (
    val tools: List<ToolDefinition> = emptyList(),
    val systemMessages: List<SystemMessageCallback> = emptyList(),
    val options: AimoChatOptions? = null,
    val messages: List<AimoChatMessage>,
)

/**
 * Aimo-owned tool callback contract for runtime tool invocation.
 *
 * Each tool callback carries its scope restrictions as a first-class property.
 * Scopes are computed at callback creation time from @Tool annotations and parent
 * @ChatService scopes. An empty [scopes] set indicates the tool is available to
 * all scopes (global tool).
 *
 * Current parsing contract for `argumentsJson`:
 * 1) Parse the raw JSON string into a JSON tree/object.
 * 2) Bind/coerce values into typed arguments for the callback implementation.
 * 3) Fail fast for binding/runtime issues (for example missing required arguments,
 *    nullability violations, or type conversion errors).
 *
 * Note: JSON Schema validation against [ToolDefinition.inputSchema] and
 * [ToolDefinition.schemaDialect] is not currently enforced by this interface.
 * Implementations may add validation, but callers must not assume schema validation
 * occurs unless explicitly documented by the concrete implementation.
 */
interface ToolCallback {
    val toolDefinition: ToolDefinition
    val scopes: Set<String>
    fun call(argumentsJson: String, context: Map<String, Any>): String
}

/**
 * Default JSON Schema dialect used when a tool definition does not specify a more
 * specific `$schema` URI in its schema document.
 */
const val DEFAULT_JSON_SCHEMA_DIALECT: String = "https://json-schema.org/draft/2020-12/schema"

/**
 * Immutable tool metadata used for model-side tool declarations and runtime validation.
 *
 * [inputSchema] uses Jackson's [JsonNode] tree type (`tools.jackson.databind.JsonNode`).
 * `JsonNode` is a structured in-memory JSON document model (object/array/value nodes),
 * not a Kotlin map wrapper, so the schema is preserved exactly as JSON.
 *
 * Storing schemas as [JsonNode] keeps this portable across providers and stable across
 * conversations, because downstream code can serialize/validate the same schema document
 * without lossy type conversions.
 */
data class ToolDefinition (
    val name: String,
    val description: String? = null,
    val inputSchema: JsonNode,
    val schemaDialect: String = DEFAULT_JSON_SCHEMA_DIALECT
)
