spring.mvc.async.request-timeout: 0s

logging:
  level:
    # Trace all Ollama client request/response and streaming event logs.
    org.ivcode.aimo: TRACE

aimo:
  # Path where chat conversations and requests are persisted (file-based DAO)
  data-dir: ./data/conversations

  # Global user ID used when accessing conversations in single-user mode
  global-user-id: ollama-user2

  model:
    ollama:
      gpt-oss:
        base-url: http://localhost:11434
        primary: true
        context:
          size: 1000
          excludeThinking: true
        options:
          model: gpt-oss:20b
          temperature: 0.7

  # Interceptor configurations
  interceptors:
    # Logging interceptor
    logging:
      enabled: true
      level: DEBUG  # TRACE, DEBUG, INFO, WARN, ERROR

