spring.mvc.async.request-timeout: 0s

logging:
  level:
    # Trace all Ollama client request/response and streaming event logs.
    org.ivcode.aimo.ollama.client: TRACE

aimo.model.ollama:
  gpt-oss:
    base-url: http://localhost:11434
    primary: true
    context:
      size: 8192
      excludeThinking: true
    options:
      model: gpt-oss:20b
      temperature: 0.7
