name: Aimo Build

on:
  push:
    branches:
      - chore/build-setup

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Test
        run: ./gradlew clean build

      - name: Prepare Pages Content
        run: |
          mkdir -p pages

          cp -r aimo-core/build/dokka/html pages/aimo-core
          cp -r aimo-model-bedrock/build/dokka/html pages/aimo-model-bedrock
          cp -r aimo-model-ollama/build/dokka/html pages/aimo-model-ollama
          cp -r aimo-plugin-ui/build/dokka/html pages/aimo-plugin-ui
          cp -r aimo-server/build/dokka/html pages/aimo-server

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4